DROP SCHEMA IF EXISTS "order" CASCADE;

CREATE SCHEMA "order";

DROP SCHEMA IF EXISTS "customer" CASCADE;

CREATE SCHEMA "customer";

DROP SCHEMA IF EXISTS "coffeeshop" CASCADE;

CREATE SCHEMA "coffeeshop";